name: Deploy to Somee via FTP
on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3
        with:
          # Sửa lại tên secret cho khớp với ảnh bạn gửi
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PW }}
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: ./
          timeout: 60000
