name: Deploy to Somee

on:
  push:
    branches:
      - main  # Kiểm tra lại xem nhánh chính của bạn là 'main' hay 'master' nhé

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Lấy code về
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Cài đặt .NET 8 (Khớp với hình ảnh bạn dùng net8.0)
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # 3. Build code ra thư mục publish
    - name: Publish
      run: dotnet publish -c Release -o ./publish

    # 4. Upload lên Somee dùng 3 Secret bạn đã tạo
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PW }}
        local-dir: ./publish/
        server-dir: /www.thanhtri.somee.com/  # Đường dẫn bắt buộc trên Somee
